### ISSUE TITLE
Use ROADMAP to give a view of the project

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#32]
This can be practice for the paper writeup, and can focus on the parts that will make the most sense to other developers
- [ ] Include the project breakdown into overall components (triple generation / offline phase, circuit evaluation / online phase, AVSS)
- [ ] explain the interface that applications use
- [ ] explain the benchmarking approach and performance goals (linear communication to prepare each gate etc)
- [ ] include some comparisons with other projects like HyperMPC, viff2, etc.

**Comment by amiller** [comment]
Dropping this. I want to release a hbmpc whitepaper this summer
