### ISSUE TITLE
VIFF double-auction app number of openings

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#49]
We would like to know how many total openings the double-auction app in VIFF takes.

**TODO**:

- [ ] Run the [double auction app](https://github.com/amiller/viff/tree/master/apps/double-auction).
   - [ ] Bypass the need for a GUI by simply feeding in dummy data.
 - [ ] Figure out the number of openings it takes.

------

_section below is a bit messy and may be outdated_

## HOW TO run the app
Running the app may not be so easy, so this issue will be used to document HOW TO to run it.

It is not clear whether there is documentation to run this app. I could not find any so far. So I just tried a few things.

There are 3 python files under the `double-auction` dir:

* `client.py`
* `server.py`
* `double-auction.py`

When _only_ running `double-auction.py`, nothing happens, e.g.: for player 3:

```bash
root@d1965ee36cbd:/usr/src/viff/apps# python double-auction/double-auction.py --no-ssl player-3.ini      
Seeding random generator with random seed 9613      
I am player 3             
Not using SSL             
Listening on port 9003    
low: 0, high: 0, last result: 0                     
Delta:  886.255 ms
```

**UPDATE**: the problem outlined below happens on Linux (Debian Stretch), @hanyunxu got it to work on Mac OS X. Also, as @amiller pointed out, let's try to bypass the need for a GUI by simply feeding in dummy data.

so I tried running the `server.py`  and `client.py`, and the `client.py` errors out with:

```bash
root@d1965ee36cbd:/usr/src/viff/apps# python double-auction/client.py                                    
Traceback (most recent call last):                  
  File "double-auction/client.py", line 18, in <module>                                                  
    from twisted.internet import gtk2reactor        
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/gtk2reactor.py", line 45, in <module>    
    import gobject        
ImportError: No module named gobject
```

I tried replacing (in `/twisted/internet/gtk2reactor.py`)

```python
# File "/usr/local/lib/python2.7/site-packages/twisted/internet/gtk2reactor.py", line 45 
import gobject
````

with

```python
# File "/usr/local/lib/python2.7/site-packages/twisted/internet/gtk2reactor.py", line 45
from gi.repository import GObject
```

but then got a different error:

```bash
root@d1965ee36cbd:/usr/src/viff/apps# python double-auction/client.py                                    
Traceback (most recent call last):                  
  File "double-auction/client.py", line 19, in <module>                                                  
    gtk2reactor.install() 
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/gtk2reactor.py", line 103, in install    
    reactor = Gtk2Reactor(useGtk)                   
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/gtk2reactor.py", line 77, in __init__    
    _glibbase.GlibReactorBase.__init__(self, gobject, _gtk, useGtk=useGtk)                               
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/_glibbase.py", line 119, in __init__     
    self._pending = self._gtk.events_pending        
  File "/usr/local/lib/python2.7/site-packages/gi/__init__.py", line 70, in __getattr__                  
    raise AttributeError(_static_binding_error)     
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

Did a bit of search online to troubleshoot the issue but did not find anything satisfactory.

### Troubleshooting Help
**UPDATE:**
1. The problem with **`PyGObject`** happens on Linux, not on Mac OS X.
2. As @amiller pointed out, let's try to bypass the need for a GUI by simply feeding in dummy data.

#### PyGObject project
* main docs: https://pygobject.readthedocs.io/en/latest/index.html
* see [Getting Started](https://pygobject.readthedocs.io/en/latest/getting_started.html) to install
* GObject reference: https://pygobject.readthedocs.io/en/latest/guide/api/gobject.html

##### To Try
- [ ] **Bypass GUI**: just feed in dummy data programmatically.
- [ ] Follow https://stackoverflow.com/questions/36247420/please-change-all-occurrences-of-import-gobject-to-from-gi-repository-import
- [ ] Downgrade `pygobject` to some prior version in which `import gobject` works (see **Downgrading** section below)
- [ ] See whether https://bugzilla.gnome.org/show_bug.cgi?id=709183 can be helpful for the problem with `from gi.repository import GObject`
- [ ] search online to see what `twisted` says about this problem

###### Downgrading `PyGObject`
It looks like the interface changed (maybe? [stackoverflow post](https://stackoverflow.com/questions/37323567/install-gobject-module)) such that instead of

```python
import gobject
```

one has to do

```python
from gi.repository import GObject
```

But the above also failed, so perhaps "downgrading" `pygobject` could work?

**Comment by hanyunx** [comment]
Solution in macOS: 
Install gtk with `brew update && brew upgrade && brew install pygtk --with-libglade`.
Then `pip install configobj`.

**Comment by amiller** [comment]
Closing this
