### ISSUE TITLE
Setup dev environment for "hyperbadgermpc" (hyperledger integration)

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#52]
This is a separate issue for the first item in #24 (https://github.com/initc3/HoneyBadgerMPC/issues/24#issuecomment-417183754):

> Docker image that builds fabric and honeybadgermpc dependencies

The "toolchain" of the hyperledger fabric project is not necessarily trivial, so this issue aims to document the progress made, and to discuss how to keep the dev setup simple for the integration.

---

Current work (in progress) is under https://github.com/sbellem/fabric/tree/hyperbadgermpc The two currently important commits are:

* https://github.com/hyperledger/fabric/commit/f70e9bfa3e9cfdcec7faaca9053dd8d19fcbc34f
* https://github.com/hyperledger/fabric/commit/e041695c930625bdf141b83b37516dd8db6965a9

Work is currently being done to run the tests on travis. There was an existing `.travis.yml` file, but seemingly outdated.

---

Some work was also done to run the fabric-sample tests on travis. It was thought that this could be useful for a potential future example for the integration. Work is under https://github.com/sbellem/fabric-samples/tree/travis, and the travis tests can be viewed under https://travis-ci.org/sbellem/fabric-samples. 

### TODO

- [x]  Add instructions to run the endorsement test locally. See https://github.com/initc3/HoneyBadgerMPC/issues/52#issuecomment-420281053 for now.
- [x] fix travis script
- [x] provide an "easy & simple" way to run the tests repeatedly without the need to re-build the required docker images -- in other words: try to simplify the docker-based toolchain to run tests when actively developing; **UPDATE**: asked some help on https://chat.hyperledger.org/channel/fabric-dev-env?msg=iuaGz9wh3tCq356bz ... in the meantime simply use the `docker-compose` command directly (e.g.: `docker-compose run --rm unit-tests ./unit-test/run.sh`) as explained below in https://github.com/initc3/HoneyBadgerMPC/issues/52#issuecomment-420281053

**Comment by sbellem** [comment]
Result of running [`honeybadgermpc.polynomial` in fabric `Endorse`](https://github.com/sbellem/fabric/blob/hyperbadgermpc/core/handlers/endorsement/builtin/default_endorsement.go#L52-L68) code: https://travis-ci.org/sbellem/fabric/builds/426840570

**Comment by sbellem** [comment]
## Dev Setup
### Prerequisites
Get the prerequisites (`git`, `go`, `docker`, `docker-compose`, `pip`) if needed. See https://hyperledger-fabric.readthedocs.io/en/latest/dev-setup/devenv.html#prerequisites for more details. You should not need vagrant.

---

**>>> IMPORTANT**: [Get a Go version >= 1.10](https://golang.org/dl/), so that running the integration tests works. 

---

### Set the GOPATH env var
See https://github.com/golang/go/wiki/SettingGOPATH and https://github.com/golang/go/wiki/GOPATH

### Clone the fabric code

```bash
mkdir -p $GOPATH/src/github.com/hyperledger
cd $GOPATH/src/github.com/hyperledger
git clone git@github.com:sbellem/fabric.git
cd fabric
git checkout hyperbadgermpc
```

### Running tests
To run the tests, some docker images and "etc" need to be built. This can be done via the `Makefile`:

```bash
make peer-docker testenv ccenv
```

#### Running the "dummy" test with `honeybadgermpc.polynomial`

```bash
make hbmpc-tests
```

the above is the equivalent of:

```bash
cd unit-test
docker-compose run --rm --no-deps unit-tests \
    go test -v \
    github.com/hyperledger/fabric/core/handlers/endorsement/builtin/... \
    -run=TestDefaultEndorsement
```

There's also an additional target to run the tests, which will also re-build the docker images (this takes time):

```bash
make hbmpc-tests-with-deps
```

#### Run all tests
Must be in project root (not in `unit-test` dir).

```bash
cd $GOPATH/src/github.com/hyperledger/fabric 
make unit-tests
```

To run in verbose mode (i.e.: `go test -v ...`):

```bash
VERBOSE=1 make unit-tests
```

**Note** that running `make unit-tests` will most likely re-build some docker images and will be time-consuming.

The `unit-test` target is defined as follows:

```makefile
unit-test: unit-test-clean peer-docker testenv ccenv
	cd unit-test && docker-compose up --abort-on-container-exit --force-recreate && docker-compose down
```

So if one does not need to run the docker related targets and etc, then one may simply execute:

```bash
cd unit-test && docker-compose up --abort-on-container-exit --force-recreate && docker-compose down
```

Or, perhaps even more explicitly:

```bash
cd unit-test
docker-compose run --rm unit-tests ./unit-test/run.sh
```

This should save some time, if one needs to run the tests, e.g. after some code edits, multiple times.

#### Running the integration tests
Make sure you have [`Go >= 1.10`](https://golang.org/dl/).

```bash
make integration-test
```

**Comment by sbellem** [comment]
Latest work (diff) can be viewed at https://github.com/hyperledger/fabric/compare/release-1.2...sbellem:hyperbadgermpc

travis CI build is at https://travis-ci.org/sbellem/fabric -- there are two jobs:
* one for honeybadgermpc specific tests
* one for all tests

**Foreseeable possibe improvements/adjustments.** For the purpose of the development activities required by the integration it may be convenient to have both code bases under the same repo, or at the very least accessible by the docker-compose file so that edits to either code base can take effect as one is developing and testing. This should be relatively straightforward to do.

**Comment by sbellem** [comment]
- [x] Try installing `honeybadgermpc` in the peer image instead of `testenv`, with the aim of making it available regardless of the environment (unit test, integration test, etc).

**NOT** working, giving up this approach.

`honeybadgermpc` needs to be available in the `hyperledger/testenv` image.

**Comment by sbellem** [comment]
Closing this issue as dev notes have been added here: https://github.com/sbellem/fabric/blob/hyperbadgermpc/HBMPC-INTEGRATION.md
